//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.Paneando.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbPaneandoEntities : DbContext
    {
        public dbPaneandoEntities()
            : base("name=dbPaneandoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<orden> ordens { get; set; }
        public virtual DbSet<pedido> pedidoes { get; set; }
        public virtual DbSet<pedido_detalle> pedido_detalle { get; set; }
        public virtual DbSet<pedido_fecha> pedido_fecha { get; set; }
        public virtual DbSet<producto> productoes { get; set; }
        public virtual DbSet<producto_precio> producto_precio { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tipo_producto> tipo_producto { get; set; }
        public virtual DbSet<venta> ventas { get; set; }
        public virtual DbSet<venta_detalle> venta_detalle { get; set; }
    }
}
