//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.Paneando.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden
    {
        public int id_orden { get; set; }
        public int id_pedido { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime fecha_despacho { get; set; }
        public byte[] hora_minuto_despacho { get; set; }
    
        public virtual pedido pedido { get; set; }
    }
}
