//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.Paneando.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido_fecha
    {
        public int id_pedido_fecha { get; set; }
        public int id_pedido { get; set; }
        public string dia_semana { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora_minuto { get; set; }
        public bool activo { get; set; }
    
        public virtual pedido pedido { get; set; }
    }
}
