//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.Paneando.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_precio
    {
        public int id_producto_precio { get; set; }
        public int id_producto { get; set; }
        public double valor_produccion { get; set; }
        public double valor_venta { get; set; }
        public bool activo { get; set; }
    
        public virtual producto producto { get; set; }
    }
}
