//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.Paneando.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public int id_venta { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal monto_total { get; set; }
        public decimal impuesto_total { get; set; }
    }
}
